---
name: MQTT IO with i2c fix
version: dev
slug: mqtt-io-with-i2c-fix
description: Expose GPIO modules and digital sensors via MQTT for remote control and monitoring.
url: https://github.com/R081n/addon-mqtt-io
arch:
    - aarch64
init: false
homeassistant_api: true
uart: true
gpio: true
privileged:
    - SYS_RAWIO
devices:
    - /dev
map:
    - config:rw
    - share:rw
    - ssl
options:
    configuration_file: /config/mqtt-io/config.yml
schema:
    configuration_file: str
    log_level: list(trace|debug|info|notice|warning|error|fatal)?
